/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as ListaIdRouteImport } from './routes/lista.$id'
import { Route as UrnaIdRouteImport } from './routes/urna.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaIdRoute = ListaIdRouteImport.update({
  id: '/lista/$id',
  path: '/lista/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UrnaIdRoute = UrnaIdRouteImport.update({
  id: '/urna/$id',
  path: '/urna/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/importar': typeof ImportarRoute
  '/lista/$id': typeof ListaIdRoute
  '/urna/$id': typeof UrnaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/importar': typeof ImportarRoute
  '/lista/$id': typeof ListaIdRoute
  '/urna/$id': typeof UrnaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/importar': typeof ImportarRoute
  '/lista/$id': typeof ListaIdRoute
  '/urna/$id': typeof UrnaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/importar' | '/lista/$id' | '/urna/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/importar' | '/lista/$id' | '/urna/$id'
  id: '__root__' | '/' | '/importar' | '/lista/$id' | '/urna/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportarRoute: typeof ImportarRoute
  ListaIdRoute: typeof ListaIdRoute
  UrnaIdRoute: typeof UrnaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista/$id': {
      id: '/lista/$id'
      path: '/lista/$id'
      fullPath: '/lista/$id'
      preLoaderRoute: typeof ListaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urna/$id': {
      id: '/urna/$id'
      path: '/urna/$id'
      fullPath: '/urna/$id'
      preLoaderRoute: typeof UrnaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportarRoute: ImportarRoute,
  ListaIdRoute: ListaIdRoute,
  UrnaIdRoute: UrnaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
